FROM ?
LABEL maintainer "Red Hat OpenShift Dedicated SRE Team"

RUN microdnf install -y python3 python3-pip
RUN pip3 install -r requirements.txt

RUN mkdir /app
WORKDIR /app

COPY . ./

ENTRYPOINT [ "/app/startup.sh" ]