kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "pagerduty-cluster-stats"
spec:
  template:
    spec:
      containers:
        - name: "pagerduty-cluster-stats"
          image: "${REGISTRY_IMG}:${IMAGE_TAG}"
  replicas: 1 