apiVersion: v1
kind: Template
parameters:
- name: ALLOWED_CIDR_BLOCKS
  required: true
- name: REGISTRY_IMG
  required: true
- name: IMAGE_TAG
  required: true
- name: REPO_NAME
  value: pagerduty_cluster_stats
  required: true
metadata:
  name: pagerduty_cluster_stats
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: pagerduty-cluster-stats
  spec:
    template:
      metadata:
        labels:
          name: frontend
      spec:
        containers:
        - name: pagerduty-cluster-stats
          image: openshift/origin-ruby-sample
          ports:
          - containerPort: 8080
            protocol: TCP
    replicas: 1
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: pagerduty-cluster-stats
  spec:
    template:
      spec:
        containers:
        - name: pagerduty-cluster-stats
          image: ${REGISTRY_IMG}:${IMAGE_TAG}
    replicas: 1
